### ISSUE TITLE
Viewing the portfolio

### ISSUE THREAD

**Issue by beatboxerish** [abhinrustagi/portfolio#1]
Can you please create a README that specifies how to run the project and view the portfolio ?

**Comment by abhinrustagi** [comment]
Hey, I've added it to github pages. 
You can visit http://abhinrustagi.github.io/portfolio/

**Comment by abhinrustagi** [comment]
It's incomplete tho rn

**Comment by beatboxerish** [comment]
Pretty nice. Just make a README.md file in your "portfolio" repo and then add the above link so that people know where to view your page.
